name: "test"
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntuTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          SKIP_DOCKER_TARGET_TEST: ${{ matrix.node == '16' && 'false' || 'true' }}

  windowsTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check engine
        run: npm run checkDepsEngineRequirements
      - name: Test
        env:
          SKIP_DOCKER_TARGET_TEST: true
        run: npm run test

  macosTest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: |
          eval "$(docker-machine env default)"
          npm run test